# Setup
title:               Logan Bartholomew
tagline:             'A personal website.'
description:         'A repository for Logan Bartholomew, which includes a resume, selected publications and presentations, project synopses, teaching resources, and contact info.'
url:                 https://loganbartholomew.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              George Logan Bartholomew
  email:             logan_bartholomew@berkeley.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
